db:
    image: mysql:latest
    ports:
        - "3333:3306"
    volumes:
        - /var/lib/mysql
    environment:
        - MYSQL_ROOT_PASSWORD=my-secret-pw
        - MYSQL_DATABASE=RSS

rss:
    image: rss
    ports:
        - "9999:8080"
        - "4444:4848"
        - "1111:8181"
    links:
        - db
    environment:
        - MYSQL_DBUSR=root
        - MYSQL_DBPASSWORD=my-secret-pw
        - MYSQL_HOST=db
        - MYSQL_PORT=3333
